"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { supabase } from "../../../../../shared/lib/supabaseClient";
import { ADMIN_EMAILS } from "../../../lib/admin";
import { theme } from "../../../../../shared/lib/theme";

const card = { background: "#fff", border: `1px solid ${theme.colors.border}`, borderRadius: 14, padding: 15 };
const input = { width: "100%", boxSizing: "border-box", padding: "9px 10px", border: `1px solid ${theme.colors.border}`, borderRadius: 8, background: "#fff", font: "inherit", fontSize: 12 };
const button = { border: 0, borderRadius: 8, padding: "8px 11px", background: theme.colors.primary, color: "#fff", fontWeight: 800, fontSize: 11, cursor: "pointer" };

export default function DriversPage() {
  const router = useRouter();
  const [checking, setChecking] = useState(true), [authorized, setAuthorized] = useState(false);
  const [drivers, setDrivers] = useState([]), [vehicles, setVehicles] = useState([]);
  const [form, setForm] = useState({ full_name: "", phone: "", email: "", vehicle_id: "" });
  const [error, setError] = useState(""), [notice, setNotice] = useState(""), [loading, setLoading] = useState(false);

  useEffect(() => { let cancelled = false; (async () => { const { data } = await supabase.auth.getSession(); const email = data?.session?.user?.email || ""; if (!data?.session) return router.replace("/login"); if (!ADMIN_EMAILS.includes(email)) return setChecking(false); if (!cancelled) { setAuthorized(true); setChecking(false); } })(); return () => { cancelled = true; }; }, [router]);

  const load = async () => { setError(""); const [{ data: ds, error: de }, { data: vs, error: ve }] = await Promise.all([
    supabase.from("drivers").select("*, vehicles(*)").order("created_at", { ascending: false }),
    supabase.from("vehicles").select("*").order("created_at", { ascending: false }),
  ]); if (de || ve) setError((de || ve).message); setDrivers(ds || []); setVehicles(vs || []); };
  useEffect(() => { if (authorized) load(); }, [authorized]);

  const usableVehicles = vehicles.filter((v) => v.active && v.status === "active");
  const stats = useMemo(() => ({ total: drivers.length, available: drivers.filter((d) => d.active !== false && d.availability_status === "available").length, assigned: drivers.filter((d) => d.vehicle_id).length, ready: drivers.filter((d) => d.active !== false && d.availability_status === "available" && d.vehicle_id && d.vehicles?.active && d.vehicles?.status === "active").length }), [drivers]);

  const addDriver = async (event) => { event.preventDefault(); setLoading(true); setError(""); setNotice(""); if (!form.full_name.trim() || !form.phone.trim()) { setError("Driver name and phone are required."); setLoading(false); return; } const { error: e } = await supabase.from("drivers").insert({ full_name: form.full_name.trim(), phone: form.phone.trim(), email: form.email.trim() || null, vehicle_id: form.vehicle_id || null, availability_status: "available" }); setLoading(false); if (e) return setError(e.message); setForm({ full_name: "", phone: "", email: "", vehicle_id: "" }); await load(); setNotice("Driver added."); };
  const updateAvailability = async (d, value) => { const { error: e } = await supabase.from("drivers").update({ availability_status: value }).eq("id", d.id); if (e) return setError(e.message); setDrivers((p) => p.map((x) => x.id === d.id ? { ...x, availability_status: value } : x)); setNotice(`${d.full_name} is now ${value}.`); };
  const assignVehicle = async (d, vehicleId) => { setError(""); setNotice(""); const { error: e } = await supabase.from("drivers").update({ vehicle_id: vehicleId || null }).eq("id", d.id); if (e) return setError(e.message); await load(); setNotice(vehicleId ? `Vehicle assigned to ${d.full_name}.` : `Vehicle removed from ${d.full_name}.`); };

  if (checking) return <main style={{ padding: 40 }}>Checking admin access…</main>;
  if (!authorized) return <main style={{ padding: 40 }}><h1>Access denied</h1><Link href="/login">Login</Link></main>;
  return <main style={{ minHeight: "100vh", background: theme.colors.bg, color: theme.colors.text, fontFamily: theme.fontFamily, padding: "28px 16px 60px" }}><div style={{ maxWidth: 1100, margin: "0 auto" }}>
    <header style={{ display: "flex", justifyContent: "space-between", gap: 12, alignItems: "end", flexWrap: "wrap", marginBottom: 18 }}><div><div style={{ fontSize: 11, color: theme.colors.primary, fontWeight: 900, letterSpacing: 1, textTransform: "uppercase" }}>VOYNU Admin · Operations</div><h1 style={{ margin: "5px 0 0", fontSize: 27 }}>Drivers</h1><p style={{ margin: "5px 0 0", color: theme.colors.textFaint, fontSize: 12 }}>Manage driver availability and the vehicle each driver is authorised to operate.</p></div><div style={{ display: "flex", gap: 8 }}><button onClick={load} style={{ ...button, background: "#fff", color: theme.colors.text, border: `1px solid ${theme.colors.border}` }}>Refresh</button><Link href="/admin" style={{ ...button, textDecoration: "none" }}>Dashboard</Link></div></header>
    {(error || notice) && <div style={{ marginBottom: 14, padding: 11, borderRadius: 9, background: error ? theme.colors.errorBg : theme.colors.primaryTint, color: error ? theme.colors.error : theme.colors.primary, fontSize: 11, fontWeight: 700 }}>{error || notice}</div>}
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(145px,1fr))", gap: 10, marginBottom: 16 }}>{[["Drivers",stats.total],["Available",stats.available],["With vehicle",stats.assigned],["Booking-ready",stats.ready]].map(([l,v]) => <div key={l} style={card}><div style={{ fontSize: 9, fontWeight: 900, color: theme.colors.textFaint, textTransform: "uppercase" }}>{l}</div><div style={{ marginTop: 5, fontSize: 24, fontWeight: 900 }}>{v}</div></div>)}</div>
    <form onSubmit={addDriver} style={{ ...card, marginBottom: 16 }}><h2 style={{ margin: "0 0 10px", fontSize: 16 }}>Add driver</h2><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 9 }}><input style={input} placeholder="Full name" value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} required/><input style={input} placeholder="Phone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} required/><input style={input} type="email" placeholder="Login email (optional)" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })}/><select style={input} value={form.vehicle_id} onChange={(e) => setForm({ ...form, vehicle_id: e.target.value })}><option value="">No vehicle yet</option>{usableVehicles.map((v) => <option key={v.id} value={v.id}>{v.registration_number} · {v.make || ""} {v.model || ""}</option>)}</select></div><button disabled={loading} type="submit" style={{ ...button, marginTop: 10 }}>{loading ? "Adding…" : "Add driver"}</button></form>
    <div style={{ display: "grid", gap: 10 }}>{drivers.map((d) => { const v = Array.isArray(d.vehicles) ? d.vehicles[0] : d.vehicles; const ready = d.active !== false && d.availability_status === "available" && d.vehicle_id && v?.active && v?.status === "active"; return <article key={d.id} style={{ ...card, borderColor: ready ? theme.colors.border : "#e8d8aa" }}><div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(170px,240px)", gap: 14, alignItems: "start" }}><div><div style={{ display: "flex", alignItems: "center", gap: 7, flexWrap: "wrap" }}><strong style={{ fontSize: 14 }}>{d.full_name}</strong><span style={{ padding: "3px 7px", borderRadius: 999, background: ready ? theme.colors.primaryTint : theme.colors.warningBg, color: ready ? theme.colors.primary : theme.colors.warning, fontSize: 8.5, fontWeight: 900 }}>{ready ? "BOOKING READY" : "NOT BOOKING READY"}</span></div><div style={{ marginTop: 5, color: theme.colors.textFaint, fontSize: 11 }}>{d.phone || "—"}{d.email ? ` · ${d.email}` : ""}{!d.user_id ? " · no login linked" : ""}</div><div style={{ marginTop: 8, padding: 9, borderRadius: 9, background: theme.colors.bg, fontSize: 11 }}>{v ? <><strong>Vehicle:</strong> {v.registration_number} · {v.make || ""} {v.model || ""} · {v.category || "—"}<br/><span style={{ color: theme.colors.textFaint }}>Vehicle status: {v.status || "—"} · {v.active ? "active" : "inactive"}</span></> : <><strong>No vehicle assigned.</strong><br/><span style={{ color: theme.colors.warning }}>This driver cannot take a booking until an active vehicle is assigned.</span></>}</div></div><div><label style={{ display: "block", fontSize: 9, fontWeight: 900, color: theme.colors.textFaint, textTransform: "uppercase" }}>Availability<select value={d.availability_status || "offline"} onChange={(e) => updateAvailability(d, e.target.value)} style={{ ...input, marginTop: 5 }}><option value="available">Available</option><option value="busy">Busy</option><option value="offline">Offline</option><option value="suspended">Suspended</option></select></label><label style={{ display: "block", marginTop: 9, fontSize: 9, fontWeight: 900, color: theme.colors.textFaint, textTransform: "uppercase" }}>Assigned vehicle<select value={d.vehicle_id || ""} onChange={(e) => assignVehicle(d, e.target.value)} style={{ ...input, marginTop: 5 }}><option value="">No vehicle</option>{usableVehicles.map((x) => <option key={x.id} value={x.id}>{x.registration_number} · {x.category || "—"}</option>)}</select></label></div></div></article>; })}</div>
    {drivers.length === 0 && <div style={{ ...card, color: theme.colors.textFaint }}>No drivers have been added yet.</div>}
  </div></main>;
}
