"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import PageHeader from "../../../../../shared/components/PageHeader";
import { supabase } from "../../../../../shared/lib/supabaseClient";
import { theme } from "../../../../../shared/lib/theme";

export default function MyRentals(){
 const [session,setSession]=useState(null),[bookings,setBookings]=useState([]),[listings,setListings]=useState([]),[payouts,setPayouts]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getSession();if(!data?.session){setLoading(false);return;}setSession(data.session);const uid=data.session.user.id;const[b,l,p]=await Promise.all([supabase.from("rental_bookings").select("*, rental_vehicle_listings(make,model,vehicle_type,city)").eq("customer_id",uid).order("created_at",{ascending:false}),supabase.from("rental_vehicle_listings").select("*, rental_vehicle_documents(document_type,verification_status,expires_at)").eq("owner_id",uid).order("created_at",{ascending:false}),supabase.from("rental_payouts").select("*").eq("owner_id",uid).order("created_at",{ascending:false})]);setBookings(b.data||[]);setListings(l.data||[]);setPayouts(p.data||[]);if(b.error||l.error||p.error)setMessage((b.error||l.error||p.error).message);setLoading(false);})();},[]);
 const card={background:"#fff",border:`1px solid ${theme.colors.border}`,borderRadius:theme.radius.lg,padding:16,boxShadow:theme.shadow.card};
 if(!session)return <><PageHeader/><main style={{minHeight:"100vh",background:theme.colors.bg,padding:30}}><div style={{...card,maxWidth:600,margin:"0 auto",textAlign:"center"}}><h1>My VOYNU Rentals</h1><p>Sign in to see your rental bookings and hosted vehicles.</p><Link href="/login" style={{display:"inline-block",padding:11,borderRadius:10,background:"#00456B",color:"#fff",textDecoration:"none",fontWeight:900}}>Sign in</Link></div></main></>;
 return <><PageHeader/><main style={{minHeight:"100vh",background:theme.colors.bg,padding:"24px 16px 60px"}}><div style={{maxWidth:1000,margin:"0 auto",display:"grid",gap:14}}><section style={{...card,background:"linear-gradient(135deg,#00456B,#0A7FA6)",color:"#fff"}}><div style={{fontSize:10,fontWeight:900,letterSpacing:1.2}}>MY RENTALS</div><h1 style={{margin:"4px 0"}}>Your rental activity</h1><p style={{margin:0,fontSize:12,opacity:.85}}>Book vehicles or earn from vehicles you list with VOYNU.</p></section>{message&&<div style={card}>{message}</div>} {loading?<div style={card}>Loading…</div>:<><section><h2>My bookings</h2><div style={{display:"grid",gap:9}}>{bookings.map(b=><div key={b.id} style={card}><strong>{b.rental_vehicle_listings?.make||"Vehicle"} {b.rental_vehicle_listings?.model||""}</strong><div style={{fontSize:11,color:theme.colors.textFaint}}>{b.rental_vehicle_listings?.vehicle_type} · {b.rental_vehicle_listings?.city} · {new Date(b.starts_at).toLocaleString()} → {new Date(b.ends_at).toLocaleString()}</div><div style={{marginTop:8,fontSize:12}}>Status <b>{b.status}</b> · Total <b>₹{Number(b.total_amount||0).toLocaleString("en-IN")}</b> · Deposit ₹{Number(b.security_deposit||0).toLocaleString("en-IN")}</div></div>)}{!bookings.length&&<div style={card}>No rental bookings yet. <Link href="/rentals">Browse vehicles</Link></div>}</div></section><section><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><h2>My hosted vehicles</h2><Link href="/rentals/host" style={{fontSize:12,fontWeight:900}}>+ Add vehicle</Link></div><div style={{display:"grid",gap:9}}>{listings.map(l=><div key={l.id} style={card}><strong>{l.make} {l.model}</strong><div style={{fontSize:11,color:theme.colors.textFaint}}>{l.vehicle_type} · {l.city} · ₹{Number(l.daily_rate||0).toLocaleString("en-IN")}/day</div><div style={{marginTop:7,fontSize:11}}>Listing: <b>{l.status}</b> · KYC/documents are reviewed before public booking.</div></div>)}{!listings.length&&<div style={card}>You have not listed a vehicle yet. <Link href="/rentals/host">List your vehicle</Link></div>}</div></section>{payouts.length>0&&<section><h2>Owner payouts</h2><div style={{display:"grid",gap:9}}>{payouts.map(p=><div key={p.id} style={{...card,display:"flex",justifyContent:"space-between"}}><span>Booking {p.booking_id.slice(0,8)}</span><b>₹{Number(p.net_amount||0).toLocaleString("en-IN")} · {p.status}</b></div>)}</div></section>}</>}</div></main></>;
}
