"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import PageHeader from "../../../../../shared/components/PageHeader";
import { supabase } from "../../../../../shared/lib/supabaseClient";
import { theme } from "../../../../../shared/lib/theme";

const input={width:"100%",padding:11,border:`1px solid #D8DEE8`,borderRadius:10,boxSizing:"border-box"};
export default function HostPage(){
 const [session,setSession]=useState(null),[owner,setOwner]=useState({full_name:"",phone:"",city:"Kanpur",address:""}),[form,setForm]=useState({vehicle_type:"car",make:"",model:"",variant:"",registration_number:"",manufacturing_year:"",city:"Kanpur",pickup_address:"",description:"",transmission:"manual",fuel_type:"petrol",seating_capacity:4,daily_rate:"",weekly_rate:"",security_deposit:"",included_km_per_day:100,excess_km_rate:"",min_rental_hours:24}),[docs,setDocs]=useState({rc:null,insurance:null,permit:null,pollution:null}),[photos,setPhotos]=useState([]),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data?.session||null));},[]);
 const setF=(k,v)=>setForm(x=>({...x,[k]:v}));
 const submit=async e=>{e.preventDefault();if(!session){setMessage("Please sign in first.");return;}setSaving(true);setMessage("");try{
   const {error:oe}=await supabase.from("rental_owner_profiles").upsert({id:session.user.id,...owner,updated_at:new Date().toISOString()});if(oe)throw oe;
   const {data:l,error:le}=await supabase.from("rental_vehicle_listings").insert({...form,owner_id:session.user.id,manufacturing_year:form.manufacturing_year?Number(form.manufacturing_year):null,seating_capacity:Number(form.seating_capacity),daily_rate:Number(form.daily_rate||0),weekly_rate:Number(form.weekly_rate||0)||null,security_deposit:Number(form.security_deposit||0),included_km_per_day:Number(form.included_km_per_day||0),excess_km_rate:Number(form.excess_km_rate||0),min_rental_hours:Number(form.min_rental_hours||24),status:"pending_review"}).select().single();if(le)throw le;
   for(const [type,file] of Object.entries(docs)){if(!file)continue;const path=`${session.user.id}/${l.id}/${type}-${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error:ue}=await supabase.storage.from("rental-documents").upload(path,file,{upsert:false});if(ue)throw ue;const {error:de}=await supabase.from("rental_vehicle_documents").insert({listing_id:l.id,owner_id:session.user.id,document_type:type,storage_path:path});if(de)throw de;}
   for(let i=0;i<photos.length;i++){const file=photos[i];const path=`${session.user.id}/${l.id}/${Date.now()}-${i}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error:ue}=await supabase.storage.from("rental-photos").upload(path,file,{upsert:false});if(ue)throw ue;const {data:u}=supabase.storage.from("rental-photos").getPublicUrl(path);const {error:pe}=await supabase.from("rental_vehicle_photos").insert({listing_id:l.id,owner_id:session.user.id,storage_path:path,photo_url:u.publicUrl,sort_order:i});if(pe)throw pe;}
   setMessage("Submitted for VOYNU approval. Your vehicle will become bookable only after owner KYC, RC/insurance and listing checks are approved.");
 }catch(err){setMessage(err.message||"Unable to submit vehicle.");}finally{setSaving(false);}};
 const card={background:"#fff",border:`1px solid ${theme.colors.border}`,borderRadius:theme.radius.lg,padding:18,boxShadow:theme.shadow.card};
 if(!session)return <><PageHeader/><main style={{minHeight:"100vh",background:theme.colors.bg,padding:30}}><div style={{...card,maxWidth:650,margin:"0 auto",textAlign:"center"}}><h1>List your vehicle and earn</h1><p>Sign in to register an unused car, bike or scooter with VOYNU.</p><Link href="/login" style={{display:"inline-block",padding:11,borderRadius:10,background:"#00456B",color:"#fff",textDecoration:"none",fontWeight:900}}>Sign in</Link></div></main></>;
 return <><PageHeader/><main style={{minHeight:"100vh",background:theme.colors.bg,padding:"24px 16px 60px"}}><form onSubmit={submit} style={{maxWidth:900,margin:"0 auto",display:"grid",gap:12}}><section style={card}><div style={{fontSize:10,fontWeight:900,color:"#0A7FA6",letterSpacing:1.2}}>VOYNU HOST</div><h1 style={{fontSize:27,margin:"4px 0"}}>Turn an unused vehicle into income.</h1><p style={{fontSize:12,color:theme.colors.textFaint}}>Register once. VOYNU verifies the owner, documents and vehicle before customers can book it.</p></section>
 <section style={card}><h2>Owner details</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10}}>{[["full_name","Full name"],["phone","Phone"],["city","City"],["address","Address"]].map(([k,l])=><label key={k} style={{fontSize:11,fontWeight:800}}>{l}<input required={k!=="address"} value={owner[k]} onChange={e=>setOwner(x=>({...x,[k]:e.target.value}))} style={{...input,marginTop:5}}/></label>)}</div></section>
 <section style={card}><h2>Vehicle</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}>{[["vehicle_type","Type",["car","bike","scooter","auto"]],["make","Make"],["model","Model"],["variant","Variant"],["registration_number","Registration number"],["manufacturing_year","Year"],["city","City"],["pickup_address","Pickup address"],["transmission","Transmission",["manual","automatic"]],["fuel_type","Fuel",["petrol","diesel","cng","electric"]],["seating_capacity","Seats"],["description","Description"]].map(([k,l,opts])=><label key={k} style={{fontSize:11,fontWeight:800}}>{l}{opts?<select value={form[k]} onChange={e=>setF(k,e.target.value)} style={{...input,marginTop:5}}>{opts.map(o=><option key={o}>{o}</option>)}</select>:<input required={!["variant","description"].includes(k)} type={k==="manufacturing_year"||k==="seating_capacity"?"number":"text"} value={form[k]} onChange={e=>setF(k,e.target.value)} style={{...input,marginTop:5}}/>}</label>)}</div></section>
 <section style={card}><h2>Pricing & availability</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:10}}>{[["daily_rate","Daily rate"],["weekly_rate","Weekly rate"],["security_deposit","Security deposit"],["included_km_per_day","Included km/day"],["excess_km_rate","Extra km rate"],["min_rental_hours","Minimum hours"]].map(([k,l])=><label key={k} style={{fontSize:11,fontWeight:800}}>{l}<input type="number" min="0" value={form[k]} onChange={e=>setF(k,e.target.value)} style={{...input,marginTop:5}}/></label>)}</div></section>
 <section style={card}><h2>Documents</h2><p style={{fontSize:11,color:theme.colors.textFaint}}>RC and valid insurance are required. Add permits/pollution documents where applicable.</p><div style={{display:"grid",gap:9}}>{[["rc","RC"],["insurance","Insurance"],["permit","Permit (if applicable)"],["pollution","PUC/Pollution (if applicable)"]].map(([k,l])=><label key={k} style={{fontSize:11,fontWeight:800}}>{l}<input type="file" accept="image/*,.pdf" required={k==="rc"||k==="insurance"} onChange={e=>setDocs(x=>({...x,[k]:e.target.files?.[0]||null}))} style={{display:"block",marginTop:5}}/></label>)}</div></section>
 <section style={card}><h2>Vehicle photos</h2><p style={{fontSize:11,color:theme.colors.textFaint}}>Upload clear exterior/interior photos. These are shown to customers after approval.</p><input type="file" accept="image/*" multiple required onChange={e=>setPhotos(Array.from(e.target.files||[]).slice(0,8))}/></section>
 {message&&<div style={{...card,fontSize:12}}>{message}</div>}<button disabled={saving} type="submit" style={{padding:13,border:0,borderRadius:11,background:"#00456B",color:"#fff",fontWeight:900}}>{saving?"Submitting…":"Submit vehicle for approval"}</button><Link href="/rentals" style={{textAlign:"center",fontSize:12}}>← Back to Rentals</Link></form></main></>;
}
