"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../../../shared/lib/supabaseClient";
import { buildWhatsAppLink } from "../../lib/contact";
import { theme } from "../../../../shared/lib/theme";
import PageHeader from "../../../../shared/components/PageHeader";
import LiveTripMap from "../../../../shared/components/LiveTripMap";

const ACTIVE_STATUSES = ["on_the_way", "arrived", "trip_started"];
const PAST_STATUSES = ["trip_completed", "cancelled"];
const labels = { pending_payment: "Payment pending", confirmed: "Booking confirmed", driver_assigned: "Driver assigned", on_the_way: "Driver on the way", arrived: "Driver arrived", trip_started: "Trip started", trip_completed: "Trip completed", cancelled: "Cancelled" };
function short(v) { return v ? v.split(",")[0].trim() || v : ""; }
function bookingId(v) { return v ? v.slice(0, 8).toUpperCase() : ""; }
function statusColor(s) { if (s === "cancelled") return { bg: theme.colors.errorBg, text: theme.colors.error }; if (s === "trip_completed") return { bg: "#e5ede8", text: "#45564c" }; if (["on_the_way", "arrived"].includes(s)) return { bg: theme.colors.warningBg, text: theme.colors.warning }; return { bg: theme.colors.primaryTint, text: theme.colors.primary }; }
function Chip({label}) { return <span style={{padding:"6px 9px",borderRadius:18,background:"#f4f7f5",border:`1px solid ${theme.colors.border}`,color:theme.colors.textMuted,fontSize:10.5,fontWeight:700}}>{label}</span>; }

export default function AccountPage() {
  const router=useRouter();
  const [checking,setChecking]=useState(true), [user,setUser]=useState(null), [bookings,setBookings]=useState([]), [loading,setLoading]=useState(false), [drivers,setDrivers]=useState({});
  useEffect(()=>{let dead=false;(async()=>{const {data}=await supabase.auth.getSession();if(!data?.session){router.replace("/login");return;}if(!dead){setUser(data.session.user);setChecking(false);}})();return()=>{dead=true;};},[router]);
  const load=async()=>{if(!user)return;setLoading(true);const {data}=await supabase.from("bookings").select("*").eq("user_id",user.id).order("travel_date",{ascending:false});setBookings(data||[]);setLoading(false);};
  useEffect(()=>{load();},[user]);
  useEffect(()=>{if(!user)return;const ch=supabase.channel(`voynu-customer-bookings-${user.id}`).on("postgres_changes",{event:"UPDATE",schema:"public",table:"bookings",filter:`user_id=eq.${user.id}`},p=>setBookings(v=>v.map(b=>b.id===p.new.id?p.new:b))).subscribe();return()=>supabase.removeChannel(ch);},[user]);
  useEffect(()=>{if(!user)return;let timer;let dead=false;const refresh=()=>{if(!dead)load();};const onVisible=()=>{if(document.visibilityState==="visible")refresh();};document.addEventListener("visibilitychange",onVisible);window.addEventListener("focus",refresh);timer=window.setInterval(()=>{if(document.visibilityState==="visible")refresh();},30000);return()=>{dead=true;document.removeEventListener("visibilitychange",onVisible);window.removeEventListener("focus",refresh);window.clearInterval(timer);};},[user]);
  const active=useMemo(()=>bookings.filter(b=>ACTIVE_STATUSES.includes(b.booking_status)),[bookings]);
  const upcoming=useMemo(()=>bookings.filter(b=>!ACTIVE_STATUSES.includes(b.booking_status)&&!PAST_STATUSES.includes(b.booking_status)),[bookings]);
  const past=useMemo(()=>bookings.filter(b=>PAST_STATUSES.includes(b.booking_status)),[bookings]);
  useEffect(()=>{if(!user)return;let dead=false;(async()=>{if(!active.length){setDrivers({});return;}const rows=await Promise.all(active.filter(b=>b.driver_id).map(async b=>{const {data}=await supabase.rpc("get_my_booking_driver",{p_booking_id:b.id});return [b.id,data||null];}));if(!dead)setDrivers(Object.fromEntries(rows));})();return()=>{dead=true;};},[user,active]);
  const driverIds=useMemo(()=>[...new Set(Object.values(drivers).map(d=>d?.driverId).filter(Boolean))],[drivers]);
  useEffect(()=>{if(!driverIds.length)return;const channels=driverIds.map(id=>supabase.channel(`voynu-location-${id}`).on("postgres_changes",{event:"UPDATE",schema:"public",table:"driver_current_location",filter:`driver_id=eq.${id}`},p=>setDrivers(v=>Object.fromEntries(Object.entries(v).map(([k,d])=>d?.driverId===id?[k,{...d,location:{lat:p.new.lat,lon:p.new.lon,updatedAt:p.new.updated_at}}]:[k,d])))).subscribe());return()=>channels.forEach(c=>supabase.removeChannel(c));},[driverIds]);
  const logout=async()=>{await supabase.auth.signOut();router.push("/");};
  const fare=b=>{const x=b.fare_breakdown;if(!x)return null;const baseFare=Number(x.baseFare)||0;const distanceFare=Number(x.distanceFare)||0;const driverAllowance=Number(x.driverAllowance)||0;const totalFare=Number(b.fare)||0;const itemizedSubtotal=baseFare+distanceFare+driverAllowance;const minimumFareAdjustment=Math.max(0,totalFare-itemizedSubtotal);const billedDistanceKm=Number(x.billedDistanceKm);return <div style={{marginTop:12,padding:"13px 14px",borderRadius:12,background:"#f7faf8",border:`1px solid ${theme.colors.border}`}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:7}}><strong style={{fontSize:11}}>Fare breakup</strong><span style={{fontSize:10,color:theme.colors.textFaint,fontWeight:700}}>Transparent pricing</span></div><div style={{display:"flex",justifyContent:"space-between",padding:"5px 0",fontSize:11.5,color:theme.colors.textMuted}}><span>Base fare</span><span>₹{baseFare.toFixed(2)}</span></div><div style={{display:"flex",justifyContent:"space-between",padding:"5px 0",fontSize:11.5,color:theme.colors.textMuted}}><span>Distance{Number.isFinite(billedDistanceKm)?` (${billedDistanceKm.toFixed(1)} km)`:""}</span><span>₹{distanceFare.toFixed(2).replace(/\.00$/,"")}</span></div>{driverAllowance>0&&<div style={{display:"flex",justifyContent:"space-between",padding:"5px 0",fontSize:11.5,color:theme.colors.textMuted}}><span>Driver allowance</span><span>₹{driverAllowance.toFixed(2).replace(/\.00$/,"")}</span></div>}<div style={{display:"flex",justifyContent:"space-between",borderTop:`1px solid ${theme.colors.border}`,paddingTop:9,marginTop:5,fontSize:12.5,fontWeight:800,color:theme.colors.textMuted}}><span>Itemized subtotal</span><span>₹{itemizedSubtotal.toFixed(2)}</span></div>{minimumFareAdjustment>0.009&&<><div style={{display:"flex",justifyContent:"space-between",padding:"6px 0",fontSize:11.5,color:theme.colors.warning,fontWeight:700}}><span>Minimum fare adjustment</span><span>₹{minimumFareAdjustment.toFixed(2)}</span></div><div style={{fontSize:10,color:theme.colors.textFaint,lineHeight:1.4}}>Minimum fare applies to this vehicle.</div></>}<div style={{display:"flex",justifyContent:"space-between",borderTop:`1px solid ${theme.colors.border}`,paddingTop:9,marginTop:7,fontSize:13,fontWeight:800}}><span>Total fare</span><span>₹{totalFare.toFixed(2).replace(/\.00$/,"")}</span></div><div style={{marginTop:7,fontSize:9.5,color:theme.colors.textFaint,lineHeight:1.4}}>No hidden charges. The adjustment shown above brings the itemized subtotal up to the applicable minimum fare when required.</div></div>;};
  const driverCard=b=>{const d=drivers[b.id];if(!d)return null;const loc=d.location;const target=b.booking_status==="trip_started"?"destination":"pickup";return <div style={{marginTop:12}}><LiveTripMap pickup={{lat:b.pickup_lat,lon:b.pickup_lon}} destination={{lat:b.drop_lat,lon:b.drop_lon}} driverLocation={loc} targetType={target} trafficEta/><div style={{marginTop:10,padding:"12px 14px",borderRadius:12,background:"#f7faf8",border:`1px solid ${theme.colors.border}`}}><div style={{fontSize:10.5,color:theme.colors.textFaint,fontWeight:800,textTransform:"uppercase"}}>Your driver</div><div style={{marginTop:5,fontSize:14,fontWeight:800}}>{d.driverName||"Driver"}</div><div style={{marginTop:3,fontSize:12,color:theme.colors.textMuted}}>{d.make||""} {d.model||""} · {d.registrationNumber||"Vehicle details unavailable"}</div><div style={{display:"flex",flexWrap:"wrap",gap:6,marginTop:9}}>{d.driverPhone&&<a href={`tel:${d.driverPhone}`} style={{padding:"6px 10px",borderRadius:20,background:"#fff",border:`1px solid ${theme.colors.border}`,color:theme.colors.primary,fontSize:11,fontWeight:800}}>Call driver</a>}{loc&&<span style={{padding:"6px 10px",borderRadius:20,background:theme.colors.primaryTint,color:theme.colors.primary,fontSize:11,fontWeight:800}}>Live location active</span>}</div><div style={{marginTop:8,fontSize:10.5,color:theme.colors.textFaint}}>{target==="destination"?"Driver is heading to your destination":b.booking_status==="arrived"?"Driver has reached the pickup area":"Driver is heading to pickup"}{loc?.updatedAt?` · Updated ${new Date(loc.updatedAt).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}`:""}</div></div></div>;};
  const card=b=>{const c=statusColor(b.booking_status), isActive=ACTIVE_STATUSES.includes(b.booking_status);return <div key={b.id} style={{padding:"16px 18px",borderRadius:theme.radius.lg,background:theme.colors.surface,border:`1px solid ${theme.colors.border}`,boxShadow:"0 8px 20px rgba(10,40,25,.05)",marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10}}><span style={{fontSize:10.5,fontWeight:700,color:theme.colors.textFaint}}>BOOKING #{bookingId(b.id)}</span><span style={{padding:"4px 10px",borderRadius:20,fontSize:10.5,fontWeight:700,background:c.bg,color:c.text}}>{labels[b.booking_status]||"Booking update"}</span></div><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4,flexWrap:"wrap"}}><i style={{width:8,height:8,borderRadius:"50%",background:theme.colors.primary}}/><span style={{fontSize:14.5,fontWeight:700}}>{short(b.pickup_name)}</span><span style={{color:"#a3b0aa"}}>→</span><i style={{width:8,height:8,borderRadius:"50%",background:theme.colors.accent}}/><span style={{fontSize:14.5,fontWeight:700}}>{short(b.drop_name)}</span></div><div style={{fontSize:11,color:theme.colors.textFaint,marginBottom:10,lineHeight:1.5}}>{b.pickup_name} → {b.drop_name}</div><div style={{display:"flex",flexWrap:"wrap",gap:6,marginBottom:10}}><Chip label={b.trip_type==="roundtrip"?"Round Trip":"One Way"}/><Chip label={`${b.travel_date} • ${b.pickup_time}`}/><Chip label={b.vehicle_type}/>{b.one_way_distance_km&&<Chip label={`${Number(b.one_way_distance_km).toFixed(1)} km`}/>}</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",paddingTop:10,borderTop:`1px dashed ${theme.colors.border}`}}><div><div style={{fontSize:10.5,color:theme.colors.textFaint,fontWeight:700}}>{b.payment_method==="upi"?"UPI Payment":"Pay on Pickup"}</div><div style={{fontSize:10,color:theme.colors.textFaint}}>{b.payment_status==="paid"?"Paid":b.payment_method==="upi"?"Verification pending":"To pay"}</div></div><div style={{fontSize:18,fontWeight:800,color:theme.colors.primary}}>₹{b.fare}</div></div>{fare(b)}{isActive&&driverCard(b)}</div>;};
  if(checking)return <main style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:theme.colors.bg}}><div style={{width:34,height:34,border:"3px solid rgba(8,120,63,.18)",borderTopColor:theme.colors.primary,borderRadius:"50%"}}/></main>;
  return <main style={{minHeight:"100vh",background:theme.colors.bg,fontFamily:theme.fontFamily,color:theme.colors.text}}><PageHeader maxWidth={theme.maxWidth.content} showAccountLink={false} whatsappHref={buildWhatsAppLink("Hi VOYNU, I need help with my account/booking.")}/><div style={{background:theme.colors.surface,borderBottom:`1px solid ${theme.colors.border}`}}><div style={{width:`min(${theme.maxWidth.content}px,calc(100% - 32px))`,margin:"0 auto",minHeight:46,display:"flex",justifyContent:"flex-end",alignItems:"center"}}><button onClick={logout} style={{padding:"7px 14px",margin:"8px 0",borderRadius:20,border:`1px solid ${theme.colors.border}`,background:"#fff",color:"#45564c",fontWeight:700}}>↪ Log out</button></div></div><div style={{width:`min(${theme.maxWidth.content}px,calc(100% - 32px))`,margin:"0 auto",padding:"24px 0 60px"}}><div style={{display:"flex",alignItems:"center",gap:14,padding:18,borderRadius:theme.radius.lg,background:theme.colors.surface,border:`1px solid ${theme.colors.border}`,boxShadow:theme.shadow.card}}><div style={{width:48,height:48,display:"flex",alignItems:"center",justifyContent:"center",borderRadius:"50%",background:theme.gradients.primary,color:"#fff",fontWeight:800,fontSize:18}}>{(user?.user_metadata?.full_name||user?.email||"?").charAt(0).toUpperCase()}</div><div><div style={{fontSize:15,fontWeight:800}}>{user?.user_metadata?.full_name||"VOYNU Customer"}</div><div style={{fontSize:12,color:theme.colors.textFaint,marginTop:2}}>{user?.email}</div></div></div><h2 style={{margin:"24px 0 12px",fontSize:15,fontWeight:800}}>Active journeys</h2>{loading?<p style={{color:theme.colors.textFaint,fontSize:13}}>Loading...</p>:active.length?active.map(card):<p style={{color:theme.colors.textFaint,fontSize:13}}>No active journeys.</p>}<h2 style={{margin:"24px 0 12px",fontSize:15,fontWeight:800}}>Upcoming journeys</h2>{upcoming.length?upcoming.map(card):<p style={{color:theme.colors.textFaint,fontSize:13}}>No upcoming bookings.</p>}<h2 style={{margin:"24px 0 12px",fontSize:15,fontWeight:800}}>Past journeys</h2>{past.length?past.map(card):<p style={{color:theme.colors.textFaint,fontSize:13}}>No past bookings yet.</p>}<div style={{textAlign:"center",marginTop:34,color:theme.colors.primary,fontWeight:800,fontSize:13}}>Need help? Chat with us on WhatsApp</div></div></main>;
}
