"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {supabase} from "../../../../shared/lib/supabaseClient";
import { isAdminUser } from "../../lib/admin";

const ACTIVE=["driver_assigned","on_the_way","arrived","trip_started","waiting_for_return","return_trip_started"];
const shortId=id=>id?id.slice(0,8).toUpperCase():"—";
const short=v=>v?v.split(",")[0].trim()||v:"—";
const money=v=>Number(v||0).toLocaleString("en-IN");
const statusLabel=v=>String(v||"").replace(/_/g," ");

export default function AdminDashboard(){
 const router=useRouter();
 const[checking,setChecking]=useState(true),[authorized,setAuthorized]=useState(false),[bookings,setBookings]=useState([]),[drivers,setDrivers]=useState([]),[vehicles,setVehicles]=useState([]),[subs,setSubs]=useState([]),[rentals,setRentals]=useState([]),[alerts,setAlerts]=useState([]),[error,setError]=useState(""),[loading,setLoading]=useState(false),[counts,setCounts]=useState(null),[firstName,setFirstName]=useState("");
 useEffect(()=>{let gone=false;(async()=>{const{data}=await supabase.auth.getSession();const email=data?.session?.user?.email||"";if(!data?.session)return router.replace("/login");if(!(await isAdminUser(email))){setChecking(false);return}if(!gone){setAuthorized(true);setChecking(false);supabase.from("profiles").select("full_name").eq("id",data.session.user.id).maybeSingle().then(({data:p})=>{if(!gone&&p?.full_name)setFirstName(p.full_name.split(" ")[0])})}})();return()=>{gone=true}},[router]);
 const load=async()=>{setLoading(true);setError("");const[{data:b,error:be},{data:d,error:de},{data:v,error:ve},{data:s,error:se},{data:r,error:re},{data:a,error:ae},{data:c,error:ce}]=await Promise.all([supabase.from("bookings").select("id,booking_status,payment_status,driver_id,trip_type,passenger_name,pickup_name,drop_name,travel_date,pickup_time,fare,created_at,trip_start_on_time,return_trip_start_on_time,trip_completion_on_time").order("created_at",{ascending:false}).limit(200),supabase.from("drivers").select("id,active,availability_status,vehicle_id"),supabase.from("vehicles").select("id,active,status"),supabase.from("commute_subscriptions").select("id,status,payment_status,total_amount,created_at").order("created_at",{ascending:false}).limit(100),supabase.from("rental_bookings").select("id,status,total_amount,created_at").order("created_at",{ascending:false}).limit(100),supabase.rpc("get_trip_timing_alerts"),supabase.rpc("admin_dashboard_counts")]);const first=be||de||ve||se||re||ae||ce;if(first)setError(first.message);setCounts(c||null);setBookings(b||[]);setDrivers(d||[]);setVehicles(v||[]);setSubs(s||[]);setRentals(r||[]);setAlerts(a||[]);setLoading(false)};
 useEffect(()=>{if(!authorized)return;load();const tick=()=>{if(!document.hidden)load()};const id=setInterval(tick,15000);document.addEventListener("visibilitychange",tick);return()=>{clearInterval(id);document.removeEventListener("visibilitychange",tick)}},[authorized]);
 const stats=useMemo(()=>({total:counts?.total??bookings.length,live:counts?.live??bookings.filter(b=>ACTIVE.includes(b.booking_status)).length,awaiting:counts?.awaiting??bookings.filter(b=>b.booking_status==="confirmed"&&!b.driver_id).length,completed:counts?.completed??bookings.filter(b=>b.booking_status==="trip_completed").length,cancelled:counts?.cancelled??bookings.filter(b=>b.booking_status==="cancelled").length,pendingPayment:counts?.pending_payment??bookings.filter(b=>b.payment_status==="pending").length,cashIssues:counts?.cash_issues??0,late:bookings.filter(b=>b.trip_start_on_time===false||b.return_trip_start_on_time===false||b.trip_completion_on_time===false).length,drivers:drivers.filter(d=>d.active!==false&&d.availability_status==="available"&&d.vehicle_id).length,vehicles:vehicles.filter(v=>v.active&&v.status==="active").length,subscriptions:subs.filter(s=>s.status!=="cancelled"&&s.status!=="completed").length}),[bookings,drivers,vehicles,subs,counts]);
 const types=useMemo(()=>({ride:stats.total,rent:rentals.length,commute:subs.filter(s=>s.status!=="cancelled").length}),[stats.total,rentals,subs]);
 const pending=useMemo(()=>[{icon:"◷",text:stats.awaiting+" booking"+(stats.awaiting>1?"s":"")+" awaiting driver assignment",href:"/admin/dispatch",action:"Assign driver",show:stats.awaiting},{icon:"₹",text:stats.pendingPayment+" booking"+(stats.pendingPayment>1?"s":"")+" with payment pending",href:"/admin/bookings?type=ride",action:"Review",show:stats.pendingPayment},{icon:"₹",text:stats.cashIssues+" cash collection"+(stats.cashIssues>1?"s":"")+" to follow up",href:"/admin/trip-monitor",action:"Review",show:stats.cashIssues},{icon:"!",text:alerts.length+" trip timing alert"+(alerts.length>1?"s":"")+" need attention",href:"/admin/trip-monitor",action:"Review",show:alerts.length},{icon:"▣",text:rentals.filter(x=>x.status==="pending_review").length+" rental approval"+(rentals.filter(x=>x.status==="pending_review").length>1?"s":"")+" pending",href:"/admin/rentals",action:"Review",show:rentals.filter(x=>x.status==="pending_review").length}].filter(x=>x.show),[stats,alerts,rentals]);
 if(checking)return <div className="adminLoading">Checking admin access…</div>;
 if(!authorized)return <div className="adminLoading"><h2>Access denied</h2><Link href="/login">Login</Link></div>;
 return <div>
  <header className="dashHead"><div><div className="dashEyebrow">VOYNU OPERATIONS</div><h1>{(()=>{const h=new Date().getHours();return h<12?"Good morning":h<17?"Good afternoon":"Good evening"})()}{firstName?", "+firstName:""}</h1><p>Here is what is happening across your mobility services.</p></div><div className="dashHeadActions"><span className="dashDate">▣ Today · {new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}</span><button onClick={load}>{loading?"Refreshing…":"↻ Refresh"}</button></div></header>
  {error&&<div className="dashError">{error}</div>}
  <section className="kpiGrid"><Kpi icon="▣" label="Total bookings" value={stats.total} note="all booking types" tone="blue"/><Kpi icon="▰" label="Live trips" value={stats.live} note="on the road now" tone="green"/><Kpi icon="◷" label="Awaiting dispatch" value={stats.awaiting} note={stats.awaiting?"needs assignment":"all clear"} tone="orange"/><Kpi icon="♙" label="Active subscriptions" value={stats.subscriptions} note="commute plans" tone="purple"/><Kpi icon="✓" label="Completed trips" value={stats.completed} note="completed bookings" tone="green"/><Kpi icon="!" label="Late events" value={stats.late} note="timing exceptions" tone="red"/><Kpi icon="♙" label="Available drivers" value={stats.drivers} note="online with vehicle" tone="blue"/><Kpi icon="▣" label="Usable vehicles" value={stats.vehicles} note="ready for dispatch" tone="green"/></section>
  <section className="overviewGrid"><div className="dashCard"><div className="cardTitle"><div><b>Bookings overview</b><small>Current operational mix</small></div><Link href="/admin/bookings?type=ride">View bookings →</Link></div><div className="mixBars"><Mix label="Ride bookings" value={types.ride} total={Math.max(types.ride+types.rent+types.commute,1)} icon="🚕"/><Mix label="Rent bookings" value={types.rent} total={Math.max(types.ride+types.rent+types.commute,1)} icon="🚗"/><Mix label="Commute subscriptions" value={types.commute} total={Math.max(types.ride+types.rent+types.commute,1)} icon="📅"/></div><div className="miniStats"><div><span>Cancelled</span><b>{stats.cancelled}</b></div><div><span>Payment pending</span><b>{stats.pendingPayment}</b></div><div><span>Timing alerts</span><b>{alerts.length}</b></div></div></div>
   <div className="dashCard"><div className="cardTitle"><div><b>Pending actions</b><small>{pending.length?pending.length+" items need attention":"Nothing needs attention"}</small></div><span className={pending.length?"attention":"clear"}>{pending.length}</span></div><div className="pendingList">{pending.length?pending.map((x,i)=><Link href={x.href} className="pendingItem" key={i}><span className="pendingIcon">{x.icon}</span><span><b>{x.text}</b><small>{x.action} →</small></span></Link>):<div className="emptyState"><span>✓</span><b>Operations are clear</b><small>No pending action is currently detected.</small></div>}</div></div>
  </section>
  <section className="overviewGrid lower"><div className="dashCard"><div className="cardTitle"><div><b>Recent bookings</b><small>Latest customer activity</small></div><Link href="/admin/bookings?type=ride">View all →</Link></div><div className="recentList">{bookings.slice(0,6).map(b=><Link href="/admin/bookings?type=ride" className="recentItem" key={b.id}><span className="recentIcon">{b.trip_type==="roundtrip"?"↔":"→"}</span><span className="recentMain"><b>#{shortId(b.id)}</b><small>{short(b.pickup_name)} → {short(b.drop_name)}</small></span><strong>₹{money(b.fare)}</strong><span className={"status status-"+b.booking_status}>{statusLabel(b.booking_status)}</span></Link>)}</div>{!bookings.length&&<div className="emptyState">No bookings found.</div>}</div>
   <div className="dashCard"><div className="cardTitle"><div><b>Live operations</b><small>{stats.live} active trip{stats.live===1?"":"s"}</small></div><Link href="/admin/trip-monitor">Open live view →</Link></div>{stats.live?<div className="liveSummary"><div className="livePulse"/><div><b>{stats.live} trip currently active</b><small>Use Live Trips for driver location, trip phase and timing.</small></div></div>:<div className="emptyState"><span>◉</span><b>No active trips</b><small>Live trips will appear here when a journey starts.</small></div>}<div className="quickLinks"><Link href="/admin/dispatch">Dispatch queue <span>→</span></Link><Link href="/admin/drivers">Driver availability <span>→</span></Link><Link href="/admin/vehicles">Fleet status <span>→</span></Link></div></div>
  </section>
  <section className="quickGrid"><Quick href="/admin/bookings?type=ride" icon="🚕" title="Ride bookings" text="Search, assign, communicate and manage rides"/><Quick href="/admin/rentals" icon="🚗" title="Rent bookings" text="Approvals, handover, active and returns"/><Quick href="/admin/subscriptions" icon="📅" title="Commute" text="Plans, requests, billing and subscriptions"/><Quick href="/admin/pricing" icon="₹" title="Pricing" text="Fare rules and operational charges"/></section>
 </div>
}
function Kpi({icon,label,value,note,tone}){return <div className="kpi"><span className={"kpiIcon "+tone}>{icon}</span><div><small>{label}</small><b>{value}</b><em>{note}</em></div></div>}
function Mix({label,value,total,icon}){const pct=Math.round(value/total*100);return <div className="mix"><span>{icon}</span><div><div className="mixTop"><b>{label}</b><strong>{value}</strong></div><div className="bar"><i style={{width:String(Math.min(pct,100))+"%"}}/></div><small>{pct}% of current workload</small></div></div>}
function Quick({href,icon,title,text}){return <Link href={href} className="quick"><span>{icon}</span><div><b>{title}</b><small>{text}</small></div><strong>→</strong></Link>}
