"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import PageHeader from "../../../../shared/components/PageHeader";
import { supabase } from "../../../../shared/lib/supabaseClient";
import { theme } from "../../../../shared/lib/theme";
import RentalDateTimeFields from "../../components/RentalDateTimeFields";

const TYPES = ["all","car","bike","scooter","auto"];
const fmt = n => `₹${Number(n||0).toLocaleString("en-IN")}`;

export default function RentalsPage(){
 const [vehicles,setVehicles]=useState([]),[type,setType]=useState("all"),[city,setCity]=useState("Kanpur"),[start,setStart]=useState(""),[end,setEnd]=useState(""),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[session,setSession]=useState(null),[booking,setBooking]=useState(null);
 const load=async()=>{setLoading(true);const {data,error}=await supabase.rpc("get_available_rental_vehicles",{p_city:city||null,p_starts_at:start?new Date(start).toISOString():null,p_ends_at:end?new Date(end).toISOString():null,p_vehicle_type:type==="all"?null:type});setVehicles(data||[]);if(error)setMessage(error.message);setLoading(false);};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data?.session||null));load();},[]);
 const reserve=async v=>{if(!session){setMessage("Please sign in before reserving a rental vehicle.");return;}if(!start||!end){setMessage("Choose pickup and return date/time first.");return;}if(new Date(end)<=new Date(start)){setMessage("Return date and time must be later than pickup.");return;}setBooking(v.id);setMessage("");const {data,error}=await supabase.rpc("create_rental_booking",{p_listing_id:v.id,p_starts_at:new Date(start).toISOString(),p_ends_at:new Date(end).toISOString(),p_payment_method:"pending"});if(error)setMessage(error.message);else setMessage(`Rental request created. Booking ${data?.id?.slice(0,8)||""} is awaiting payment confirmation.`);setBooking(null);load();};
 const card={background:"#fff",border:`1px solid ${theme.colors.border}`,borderRadius:theme.radius.lg,padding:22,boxShadow:theme.shadow.card};
 return <><PageHeader/><main style={{minHeight:"100vh",background:theme.colors.bg,color:theme.colors.text,padding:"24px 16px 60px"}}><div style={{maxWidth:1100,margin:"0 auto"}}><section style={{...card,background:"var(--voynu-gradient)",color:"#fff",padding:30,marginBottom:16}}><div style={{fontSize:theme.type.eyebrow.size,fontWeight:theme.type.eyebrow.weight,letterSpacing:theme.type.eyebrow.letterSpacing}}>VOYNU RENTALS</div><h1 style={{fontSize:32,fontWeight:800,letterSpacing:-0.6,margin:"8px 0"}}>Rent a vehicle. Earn from yours.</h1><p style={{fontSize:14.5,lineHeight:1.6,opacity:.9,maxWidth:650,margin:"0 0 18px"}}>Cars, bikes and scooters from verified owners. Transparent rental price, security deposit and included kilometres before you book.</p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><Link href="/rentals/host" style={{background:"#fff",color:"var(--voynu-navy)",padding:"13px 20px",borderRadius:12,textDecoration:"none",fontWeight:900,fontSize:13}}>List your vehicle &amp; earn</Link><Link href="/account" style={{color:"#fff",padding:"13px 20px",border:"1.5px solid rgba(255,255,255,.4)",borderRadius:12,textDecoration:"none",fontWeight:800,fontSize:13}}>My account</Link></div></section>
 <section style={{...card,marginBottom:16}}><div style={{fontSize:26,fontWeight:800,letterSpacing:-0.4,color:"var(--voynu-navy)",marginBottom:6}}>Find a rental</div><div style={{fontSize:13.5,lineHeight:1.5,color:theme.colors.textMuted,marginBottom:22}}>Choose your city, pickup and return date &amp; time, then select a vehicle type.</div><div className="voynu-rental-search-grid"><label style={{fontSize:11,fontWeight:800,letterSpacing:0.3,textTransform:"uppercase",color:theme.colors.textMuted}}>City<div style={{display:"flex",alignItems:"center",gap:12,marginTop:8,padding:"0 16px",height:60,border:`1.5px solid ${theme.colors.borderStrong}`,borderRadius:17,background:"linear-gradient(180deg,#fbfdfc,#f6faf7)",boxShadow:"0 3px 12px rgba(18,70,43,.045)"}}><span style={{width:40,height:40,flex:"0 0 40px",display:"flex",alignItems:"center",justifyContent:"center",borderRadius:12,background:"var(--voynu-primary-tint)",fontSize:19}}>📍</span><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Kanpur" style={{flex:1,minWidth:0,border:0,outline:"none",background:"transparent",fontSize:16,fontWeight:700,color:"var(--voynu-navy)",fontFamily:"inherit"}}/></div></label><RentalDateTimeFields start={start} end={end} onStartChange={v=>{setStart(v);if(end&&new Date(end)<=new Date(v))setEnd("")}} onEndChange={setEnd}/></div><div style={{display:"flex",gap:9,marginTop:22,flexWrap:"wrap",alignItems:"center"}}>{TYPES.map(t=><button key={t} onClick={()=>setType(t)} style={{padding:"12px 18px",borderRadius:999,border:`1.5px solid ${type===t?"var(--voynu-teal)":theme.colors.border}`,background:type===t?"var(--voynu-primary-tint)":"#fff",color:"var(--voynu-navy)",fontWeight:800,fontSize:13,textTransform:"capitalize",boxShadow:type===t?"0 0 0 2px rgba(10,127,166,.08)":"none"}}>{t}</button>)}<button onClick={load} style={{marginLeft:"auto",padding:"14px 24px",border:0,borderRadius:13,background:"var(--voynu-gradient)",color:"#fff",fontWeight:900,fontSize:13.5,boxShadow:"0 10px 24px rgba(10,127,166,.18)"}}>Search vehicles</button></div></section>
 {message&&<div style={{...card,marginBottom:12,fontSize:12}}>{message}</div>}
 {loading?<div style={card}>Finding approved vehicles…</div>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12}}>{vehicles.map(v=><article key={v.id} style={card}>{v.photo_url?<img src={v.photo_url} alt="Vehicle" style={{width:"100%",height:170,objectFit:"cover",borderRadius:12,marginBottom:11}}/>:<div style={{height:170,borderRadius:12,background:"var(--voynu-primary-tint)",display:"grid",placeItems:"center",fontSize:48,marginBottom:11}}>🚗</div>}<div style={{fontSize:10,textTransform:"uppercase",fontWeight:900,color:"var(--voynu-teal)"}}>{v.vehicle_type} · {v.city}</div><h2 style={{fontSize:18,margin:"4px 0"}}>{v.make||"Vehicle"} {v.model||""} {v.variant||""}</h2><div style={{fontSize:12,color:theme.colors.textFaint}}>{v.transmission||"Standard"} · {v.fuel_type||"Fuel"} · {v.seating_capacity||2} seats</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,margin:"14px 0",fontSize:11}}><div>From <b>{fmt(v.daily_rate)}/day</b></div><div>Deposit <b>{fmt(v.security_deposit)}</b></div><div>Included <b>{v.included_km_per_day} km/day</b></div><div>Extra <b>{fmt(v.excess_km_rate)}/km</b></div></div><button onClick={()=>reserve(v)} disabled={booking===v.id} style={{width:"100%",padding:11,border:0,borderRadius:10,background:"var(--voynu-navy)",color:"#fff",fontWeight:900}}>{booking===v.id?"Creating…":"Reserve vehicle"}</button></article>)}{!vehicles.length&&<div style={card}>No approved vehicles are available for these filters and dates. Try another date, vehicle type or city.</div>}</div>}</div></main></>;
}
