"use client";
import { useEffect, useState } from "react";
import { supabase } from "../../../../../shared/lib/supabaseClient";
import { theme } from "../../../../../shared/lib/theme";

const c = theme.colors;
const card = { background:c.surface, border:"1px solid "+c.border, borderRadius:18, padding:16, boxShadow:theme.shadow.card };
const input = { width:"100%", minHeight:42, marginTop:5, padding:"0 10px", boxSizing:"border-box", border:"1px solid "+c.borderStrong, borderRadius:11, background:c.surface, color:c.text, font:"inherit", fontSize:13 };
const primary = { minHeight:42, padding:"0 16px", border:0, borderRadius:11, background:theme.gradients.primary, color:"#fff", font:"inherit", fontWeight:800, cursor:"pointer" };

const emptyForm = () => ({ id:null, code:"", description:"", discount_type:"fixed", discount_value:"", max_discount:"", min_booking_amount:"0", starts_at:"", expires_at:"", active:true, usage_limit:"", per_user_limit:"1", oneway:true, roundtrip:true });

function toLocal(value) { return value ? new Date(value).toISOString().slice(0,16) : ""; }
function toIso(value) { return value ? new Date(value).toISOString() : null; }

export default function CouponsAdminPage() {
  const [rows,setRows]=useState([]); const [form,setForm]=useState(emptyForm()); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  async function load(){ setError(""); const {data,error:e}=await supabase.from("coupons").select("*").order("created_at",{ascending:false}); if(e)setError(e.message); else setRows(data||[]); }
  useEffect(()=>{load();},[]);
  function edit(row){ setForm({...row, code:row.code||"", discount_value:String(row.discount_value??""), max_discount:row.max_discount==null?"":String(row.max_discount), min_booking_amount:String(row.min_booking_amount??0), starts_at:toLocal(row.starts_at), expires_at:toLocal(row.expires_at), usage_limit:row.usage_limit==null?"":String(row.usage_limit), per_user_limit:String(row.per_user_limit??1), oneway:(row.applicable_trip_types||[]).includes("oneway"), roundtrip:(row.applicable_trip_types||[]).includes("roundtrip")}); setMessage(""); setError(""); }
  async function save(e){ e.preventDefault(); setError(""); setMessage(""); if(!form.code.trim())return setError("Coupon code is required."); if(!form.discount_value || Number(form.discount_value)<=0)return setError("Discount value must be greater than zero."); const trips=[form.oneway&&"oneway",form.roundtrip&&"roundtrip"].filter(Boolean); if(!trips.length)return setError("Select at least one trip type."); setBusy(true); const {data,error:e2}=await supabase.rpc("admin_upsert_coupon",{p_id:form.id,p_code:form.code.trim().toUpperCase(),p_description:form.description.trim()||null,p_discount_type:form.discount_type,p_discount_value:Number(form.discount_value),p_max_discount:form.max_discount===""?null:Number(form.max_discount),p_min_booking_amount:Number(form.min_booking_amount||0),p_starts_at:toIso(form.starts_at),p_expires_at:toIso(form.expires_at),p_active:Boolean(form.active),p_usage_limit:form.usage_limit===""?null:Number(form.usage_limit),p_per_user_limit:Number(form.per_user_limit||1),p_applicable_trip_types:trips}); if(e2)setError(e2.message); else {setMessage("Coupon saved."); setForm(emptyForm()); await load();} setBusy(false); }
  async function toggle(row){ setBusy(true); setError(""); const {error:e}=await supabase.rpc("admin_upsert_coupon",{p_id:row.id,p_code:row.code,p_description:row.description,p_discount_type:row.discount_type,p_discount_value:Number(row.discount_value),p_max_discount:row.max_discount==null?null:Number(row.max_discount),p_min_booking_amount:Number(row.min_booking_amount||0),p_starts_at:row.starts_at,p_expires_at:row.expires_at,p_active:!row.active,p_usage_limit:row.usage_limit==null?null:Number(row.usage_limit),p_per_user_limit:Number(row.per_user_limit||1),p_applicable_trip_types:row.applicable_trip_types||["oneway","roundtrip"]}); if(e)setError(e.message); else await load(); setBusy(false); }
  return <main style={{background:c.bg,minHeight:"70vh",color:c.text,fontFamily:theme.fontFamily,padding:"4px 2px 88px"}}><div style={{maxWidth:900,margin:"0 auto"}}><header style={{margin:"6px 0 16px"}}><div style={{color:c.primary,fontSize:10.5,fontWeight:900,letterSpacing:1}}>PROMOTIONS</div><h1 style={{margin:"4px 0 0",fontSize:26}}>Coupons</h1><p style={{margin:"5px 0 0",color:c.textFaint,fontSize:12.5}}>Create and control customer promo codes. Final discount validation happens on the booking server.</p></header>
  {error&&<div style={{...card,marginBottom:12,color:c.error,background:c.errorBg}}>{error}</div>}{message&&<div style={{...card,marginBottom:12,color:c.success,background:c.successBg}}>{message}</div>}
  <form onSubmit={save} style={{...card,marginBottom:14}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:11}}>
  <label style={{fontSize:11.5,fontWeight:700}}>Code<input value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} placeholder="WELCOME100" style={input}/></label>
  <label style={{fontSize:11.5,fontWeight:700}}>Discount type<select value={form.discount_type} onChange={e=>setForm({...form,discount_type:e.target.value})} style={input}><option value="fixed">Fixed ₹</option><option value="percent">Percentage %</option></select></label>
  <label style={{fontSize:11.5,fontWeight:700}}>Discount value<input type="number" min="0" step="0.01" value={form.discount_value} onChange={e=>setForm({...form,discount_value:e.target.value})} style={input}/></label>
  <label style={{fontSize:11.5,fontWeight:700}}>Max discount (optional)<input type="number" min="0" step="0.01" value={form.max_discount} onChange={e=>setForm({...form,max_discount:e.target.value})} style={input}/></label>
  <label style={{fontSize:11.5,fontWeight:700}}>Minimum booking<input type="number" min="0" step="1" value={form.min_booking_amount} onChange={e=>setForm({...form,min_booking_amount:e.target.value})} style={input}/></label>
  <label style={{fontSize:11.5,fontWeight:700}}>Usage limit<input type="number" min="1" step="1" value={form.usage_limit} onChange={e=>setForm({...form,usage_limit:e.target.value})} placeholder="Unlimited" style={input}/></label>
  <label style={{fontSize:11.5,fontWeight:700}}>Uses per customer<input type="number" min="1" step="1" value={form.per_user_limit} onChange={e=>setForm({...form,per_user_limit:e.target.value})} style={input}/></label>
  <label style={{fontSize:11.5,fontWeight:700}}>Starts<input type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})} style={input}/></label>
  <label style={{fontSize:11.5,fontWeight:700}}>Expires<input type="datetime-local" value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value})} style={input}/></label>
  </div><label style={{display:"block",marginTop:11,fontSize:11.5,fontWeight:700}}>Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Short customer-facing offer description" style={input}/></label>
  <div style={{display:"flex",gap:16,flexWrap:"wrap",marginTop:12,fontSize:12}}><label><input type="checkbox" checked={form.oneway} onChange={e=>setForm({...form,oneway:e.target.checked})}/> One-way</label><label><input type="checkbox" checked={form.roundtrip} onChange={e=>setForm({...form,roundtrip:e.target.checked})}/> Round trip</label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label></div>
  <div style={{display:"flex",gap:8,marginTop:14}}><button disabled={busy} type="submit" style={{...primary,flex:1}}>{form.id?"Update coupon":"Create coupon"}</button>{form.id&&<button type="button" onClick={()=>setForm(emptyForm())} style={{...primary,background:c.surface,color:c.text,border:"1px solid "+c.border}}>Cancel edit</button>}</div></form>
  <section style={card}><h2 style={{margin:0,fontSize:15}}>Existing coupons</h2><div style={{display:"grid",gap:9,marginTop:12}}>{rows.length===0?<p style={{margin:0,color:c.textFaint,fontSize:12}}>No coupons have been created yet.</p>:rows.map(row=><div key={row.id} style={{padding:13,border:"1px solid "+c.border,borderRadius:13,background:"rgba(255,255,255,.55)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><strong style={{fontSize:14,letterSpacing:.4}}>{row.code}</strong><div style={{marginTop:3,color:c.textFaint,fontSize:10.5}}>{row.discount_type==="percent"?row.discount_value+"% off":"₹"+Number(row.discount_value).toLocaleString("en-IN")+" off"} · min ₹{Number(row.min_booking_amount||0).toLocaleString("en-IN")} · {row.per_user_limit} use/customer</div></div><div style={{display:"flex",gap:7}}><button type="button" onClick={()=>edit(row)} style={{...primary,minHeight:36,padding:"0 12px",fontSize:11}}>Edit</button><button type="button" disabled={busy} onClick={()=>toggle(row)} style={{...primary,minHeight:36,padding:"0 12px",fontSize:11,background:row.active?c.surface:theme.gradients.primary,color:row.active?c.text:"#fff",border:row.active?"1px solid "+c.border:"0"}}>{row.active?"Disable":"Enable"}</button></div></div><div style={{marginTop:8,color:row.active?c.success:c.textFaint,fontSize:10.5,fontWeight:800}}>{row.active?"ACTIVE":"INACTIVE"} · {row.usage_limit==null?"Unlimited uses":row.usage_limit+" total uses"}</div></div>)}</div></section>
  </div></main>;
}
