"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { theme } from "../lib/theme";
import AccountLink from "./AccountLink";
import NotificationBell from "./NotificationBell";

function IconWhatsApp({ size = 15 }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor"><path d="M12 2a10 10 0 0 0-8.6 15L2 22l5.2-1.4A10 10 0 1 0 12 2zm0 18.2a8.1 8.1 0 0 1-4.2-1.2l-.3-.2-3.1.8.8-3-.2-.3A8.2 8.2 0 1 1 12 20.2zm4.5-6.1c-.2-.1-1.5-.7-1.7-.8-.2-.1-1.5-.7-1.7-.8-.2-.1-.4.1-.6.1s-.7.8-.9 1c-.2.2-.3.2-.5.1a6.7 6.7 0 0 1-2-1.2 7.4 7.4 0 0 1-1.4-1.7c-.1-.2 0-.4.1-.5l.4-.4c.1-.1.2-.3.2-.4a.5.5 0 0 0 0-.5c-.1-.1-.6-1.5-.9-2-.2-.5-.4-.4-.6-.4h-.5a1 1 0 0 0-.7.3 3 3 0 0 0-1 2.3c0 1.3 1 2.6 1.1 2.8.1.2 2 3.1 4.9 4.3a16 16 0 0 0 1.6.6 3.9 3.9 0 0 0 1.8.1c.5-.1 1.5-.6 1.7-1.2.2-.6.2-1.1.2-1.2-.1-.1-.3-.2-.5-.3z" /></svg>; }

export default function PageHeader({ maxWidth = theme.maxWidth.content, showAccountLink = true, showWhatsapp = true, whatsappHref = null }) {
  const pathname = usePathname();
  const isHome = pathname === "/";
  const isSubscription = pathname?.startsWith("/subscriptions");
  return <header className="voynuPageHeader" style={{background:"rgba(255,255,255,0.96)",backdropFilter:"blur(12px)",borderBottom:`1px solid ${theme.colors.border}`,position:"sticky",top:0,zIndex:20}}>
    <div className="voynuPageHeaderInner" style={{width:`min(${maxWidth}px, calc(100% - 32px))`,margin:"0 auto",minHeight:68,display:"flex",alignItems:"center",justifyContent:"space-between",gap:12}}>
      <Link href="/" className="voynuHeaderBrand" style={{display:"flex",alignItems:"center",gap:10,textDecoration:"none",minWidth:0,flexShrink:1}}><img src="/icon.svg" alt="VOYNU" width="40" height="40" style={{borderRadius:11,display:"block",boxShadow:"0 6px 14px rgba(10,35,55,.16)"}}/><span className="voynuHeaderBrandWord" style={{color:theme.colors.navy,fontWeight:800,fontSize:19,letterSpacing:"-0.4px"}}>VOYNU</span></Link>
      <div className="voynuHeaderActions" style={{display:"flex",alignItems:"center",gap:8,flexShrink:0}}><Link className="voynuHeaderAction" href="/" aria-label="Book a ride" style={{display:"flex",alignItems:"center",padding:"9px 12px",borderRadius:theme.radius.pill,background:isHome?theme.colors.primaryTint:theme.colors.surface,color:theme.colors.primaryDark,border:`1px solid ${isHome?theme.colors.primary:theme.colors.borderStrong}`,fontSize:12,fontWeight:800,textDecoration:"none"}}>Ride</Link><Link className="voynuHeaderAction" href="/subscriptions" aria-label="Daily commute subscriptions" style={{display:"flex",alignItems:"center",padding:"9px 12px",borderRadius:theme.radius.pill,background:isSubscription?theme.colors.primaryTint:theme.colors.surface,color:theme.colors.primaryDark,border:`1px solid ${isSubscription?theme.colors.primary:theme.colors.borderStrong}`,fontSize:12,fontWeight:800,textDecoration:"none"}}>Commute</Link><Link className="voynuHeaderAction" href="/rentals" aria-label="Rent a vehicle" style={{display:"flex",alignItems:"center",padding:"9px 12px",borderRadius:theme.radius.pill,background:pathname?.startsWith("/rentals")?theme.colors.primaryTint:theme.colors.surface,color:theme.colors.primaryDark,border:`1px solid ${pathname?.startsWith("/rentals")?theme.colors.primary:theme.colors.borderStrong}`,fontSize:12,fontWeight:800,textDecoration:"none"}><span>Rent</span></Link><NotificationBell />{showAccountLink&&<div className="voynuHeaderAccount"><AccountLink/></div>}{showWhatsapp&&<a className="voynuHeaderWhatsapp" href={whatsappHref||"https://wa.me/919123456789?text="+encodeURIComponent("Hi VOYNU, I have a question.")} target="_blank" rel="noopener noreferrer" style={{display:"flex",alignItems:"center",gap:7,padding:"9px 15px",borderRadius:theme.radius.pill,background:"#22C55E",color:"#fff",fontSize:12.5,fontWeight:700,boxShadow:"0 6px 16px rgba(34,197,94,.22)"}}><IconWhatsApp size={14}/><span className="whatsappLabel">Chat with us</span></a>}</div>
    </div>
    {isHome && <div className="homeProductBar"><div className="homeProductInner"><div><strong>How do you want to travel?</strong><span>Ride with a driver, commute daily, or rent a vehicle.</span></div><div className="homeProductSwitch"><Link href="/" className="homeProductOption active"><span>🚕</span><span><b>Ride</b><small>We drive. You relax.</small></span></Link><Link href="/subscriptions" className="homeProductOption"><span>📅</span><span><b>Commute</b><small>Daily route plans</small></span></Link><Link href="/rentals" className="homeProductOption"><span>🚗</span><span><b>Rent</b><small>You drive. You decide.</small></span></Link></div></div></div>}
    <style jsx>{` .homeProductBar{border-top:1px solid ${theme.colors.border};background:${theme.colors.surface}} .homeProductInner{width:min(${maxWidth}px,calc(100% - 32px));margin:0 auto;padding:9px 0;display:flex;align-items:center;justify-content:space-between;gap:14px}.homeProductInner>div:first-child{display:flex;flex-direction:column;gap:1px}.homeProductInner strong{font-size:11px;color:${theme.colors.text};letter-spacing:-.1px}.homeProductInner span{font-size:9.5px;color:${theme.colors.textMuted}}.homeProductSwitch{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;padding:3px;border-radius:14px;background:${theme.colors.bg};border:1px solid ${theme.colors.border};min-width:390px}.homeProductOption{display:flex;align-items:center;justify-content:center;gap:7px;padding:7px 10px;border-radius:10px;text-decoration:none;color:${theme.colors.textMuted};transition:.18s ease}.homeProductOption.active{background:${theme.gradients.primary};color:#fff;box-shadow:0 5px 14px rgba(10,127,166,.18)}.homeProductOption b,.homeProductOption small{display:block}.homeProductOption b{font-size:10.5px}.homeProductOption small{font-size:8px;margin-top:1px;opacity:.8}.homeProductOption>span:first-child{font-size:14px}@media(max-width:760px){.homeProductInner{width:calc(100% - 20px);padding:8px 0;display:block}.homeProductInner>div:first-child{margin-bottom:7px}.homeProductSwitch{min-width:0;width:100%}}@media(max-width:700px){.voynuPageHeaderInner{width:100%!important;padding:8px 10px;min-height:62px!important;gap:6px!important}.voynuHeaderBrand{gap:7px!important}.voynuHeaderBrand img{width:34px!important;height:34px!important}.voynuHeaderBrandWord{font-size:16px!important}.voynuHeaderActions{gap:4px!important;min-width:0}.voynuHeaderAction{padding:8px 9px!important;font-size:11px!important}.voynuHeaderWhatsapp{padding:8px 10px!important}}@media(max-width:520px){.voynuHeaderBrandWord{display:none}.voynuHeaderAccount :global(a){padding:8px 9px!important;font-size:11px!important}.voynuHeaderWhatsapp .whatsappLabel{display:none}.voynuHeaderWhatsapp{padding:8px 9px!important}.homeProductInner span{font-size:8.5px}.homeProductOption{padding:6px 5px;gap:5px}.homeProductOption>span:first-child{font-size:12px}.homeProductOption b{font-size:10px}.homeProductOption small{font-size:7px}}@media(max-width:400px){.voynuHeaderActions{gap:3px!important}.voynuHeaderAction{padding:7px 8px!important}.voynuHeaderAccount :global(a){padding:7px 8px!important}.voynuHeaderWhatsapp{padding:7px 8px!important}.voynuPageHeaderInner{padding-inline:8px}} .whatsappLabel{display:inline}@media(max-width:520px){.whatsappLabel{display:none}}`}</style>
  </header>;
}
